config/routes.rb
Rails.application.routes.draw do
  resources :couriers do
    resources :packages, only: %i[create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
# frozen_string_literal: true

class Courier < ApplicationRecord
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :name, presence: true, length: { minimum: 3 }

  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_many :packages, dependent: :destroy
end

app/models/package.rb
# frozen_string_literal: true

class Package < ApplicationRecord
  belongs_to :courier

  validates :tracking_number, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
end

app/controllers/couriers_controller.rb
# frozen_string_literal: true

class CouriersController < ApplicationController
  before_action :set_courier, except: %i[create new index]

  def index
    @couriers = Courier.all.reverse
  end

  def new
    @courier = Courier.new
  end

  def show; end

  def create
    @courier = Courier.new(courier_params)

    if @courier.save
      redirect_to couriers_path, notice: 'Courier was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @courier.update(courier_params)
      redirect_to @courier, notice: 'Courier was successfully updated.'
    else
      render :edit, notice: @courier.errors.full_messages
    end
  end

  def destroy
    @courier.destroy

    redirect_to couriers_path, notice: 'Courier was deleted.'
  end
end

private

def courier_params
  params.require(:courier).permit(:name, :email)
end

def set_courier
  @courier = Courier.find(params[:id])
end

app/controllers/packages_controller.rb
# frozen_string_literal: true

class PackagesController < ApplicationController
  def create
    courier = Courier.find(params[:courier_id])
    @package = courier.packages.new(package_params)
    if @package.save
      redirect_to courier_path(courier), notice: 'Package was successfully created'
    else
      redirect_to courier_path(courier), notice: @package.errors.full_messages.first
    end
  end

  private

  def package_params
    params.require(:package).permit(:tracking_number, :delivery_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
# frozen_string_literal: true

module CouriersHelper
end

app/helpers/packages_helper.rb
# frozen_string_literal: true

module PackagesHelper
end

app/views/couriers/_all.html.erb
  <div class="courier-<%= courier.id %>">
    <strong>Id:</strong>
    <%= courier.id %><br />
    <strong>Name:</strong>
    <%= courier.name %><br />
    <strong>Email:</strong>
    <%= courier.email %></td>
    <br />
    <%= link_to 'Show', courier_path(courier) %>
    <%= link_to 'Edit', edit_courier_path(courier) %>
    <%= link_to 'Delete', courier_path(courier), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
<br/>

app/views/couriers/_form.html.erb
<%= form_with(model: @courier, local: true) do |f| %>
  <% if @courier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@courier.errors.count, "error") %> prohibited this courier from being saved:</h2>

      <ul>
      <% @courier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :name, placeholder: true, required: true %>
  <%= f.text_field :email, placeholder: true, required: true%>
  <%= f.button :Submit %>
<% end %>

app/views/couriers/destroy.html.erb
<h1>Couriers#destroy</h1>
<p>Find me in app/views/couriers/destroy.html.erb</p>

app/views/couriers/edit.html.erb
<%= render 'form', courier: @courier %>

app/views/couriers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Couriers</h1>

<p><%= link_to 'New', new_courier_path %></p>

<%= render partial: 'couriers/all', collection: @couriers, as: :courier %>

app/views/couriers/new.html.erb
<div class="text-center">
  <%= render 'couriers/form' %>
</div>

app/views/couriers/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <strong>
  <%= @courier.name %>
  <%= @courier.email %>
  </strong>
  <%= link_to 'Back', couriers_path %>
</div>

<%= render 'packages/form', courier: @courier %>

<table>
  <thead>
    <tr>
      <th>Tracking number</th>
      <th>Delivery status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <%= render partial: 'packages/all', collection: @courier.packages.reverse, as: :package %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>